### ISSUE TITLE
Spaces removed around link

### ISSUE THREAD

**Issue by mebrett** [mebrett/bannerMessage#1]
Despite there being spaces in the text, in public view the link runs together with the words before and behind it.

**Comment by kimisgold** [comment]
The  `#content-warning-banner` uses flexbox. In the original module, it was to center align the text and button both vertically and horizontally. It also eliminates any excess horizontal spacing that's automatically included for for inline content, causing the weirdness you're seeing here. The easiest way to restores that spacing is to wrap the text in a `<span>` or remove the `display:flex` from`#content-warning-banner`, especially if you don't need any buttons or similar content. In the latter case, you'd also need to `text-align:center`.
